# Создание массивов

In [1]:
import numpy as np

## Создание массива из последовательностей Python

Преобразование осуществляется функцией [`np.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array).

Одномерный массив:

In [2]:
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

Двумерный массив:

In [3]:
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

Трёхмерный массив:

In [4]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Можно явно указать тип чисел (данных) массива.
Делается это с помощью указания параметра `dtype`:

In [5]:
a = np.array([1, 2, 3], dtype=float)
a

array([1., 2., 3.])

## NumPy-способы создания одномерных массивов

Для создания одномерных массивов в NumPy имеются такие функции, как [`np.linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace) и [`np.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange).

Функция `np.arange` создаёт массив по заданным началу, концу и шагу - `np.arange(start, stop, step)`:

In [6]:
# Указан только конец интервала (stop).
# Начало по умолчанию принято за 0.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# (start, stop)
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
# int (start, stop, step)
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [10]:
# float (start, stop, step)
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

```{warning}
По умолчанию конец интервала (3 в последнем случае) не входит в итоговый массив.
Однако из-за ошибок округления компьютером вещественных чисел это иногда может случаться.
Всегда стоит об этом помнить.
```

Функция `np.linspace` создаёт массив по заданным началу, концу и числу точек, равномерно расположенных от начального до конечного значения:

In [11]:
# (начало, конец, число точек)
np.linspace(1, 4, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

```{note}
В отличие от `np.arange` последнее значение всегда входит в созданный массив.
```

## NumPy-способы создания двумерных массивов

Для создания двумерных массивов имеются следующие функции: [`np.eye`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye), [`np.diag`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html#numpy.diag) и [`np.vander`](https://numpy.org/doc/stable/reference/generated/numpy.vander.html#numpy.vander).

Функция `np.eye` инициализирует единичную матрицу.
В общем случае можно сгенерировать и прямоугольную матрицу $\mathbf{A}$, у которой все элементы равны нулю, кроме единиц, стоящих в псевдодиагонали, где индекс строки $i$ совпадает с индексом столбца $j$: $a_{i j} = 1$ при $i = j$ и $a_{i j} = 0$ при $i \neq j$.

In [12]:
# Единичная матрица 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# То же, но целочисленный вариант
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
# Прямоугольный вариант
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

Функция `np.diag` по переданному одномерному массиву (списку, кортежу) создаёт диагональную матрицу, на диагонали которой расположены элементы переданного массива:

In [15]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [16]:
# С указанием смещения от главной диагонали
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [17]:
# Получение диагонали любой матрицы
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

Функция `np.vander` несколько специфична - она создаёт [матрицу Вандермонда](https://ru.wikipedia.org/wiki/Определитель_Вандермонда).
С помощью этой функции по переданному массиву `a` длины $m$ создаётся матрица с $n$ столбцами, каждый столбец которой является переданным массивом `a`, каждый элемент которого возведён в степень $n - j - 1$, где $j$ - индекс столбца:

In [18]:
# (a, n)
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [19]:
# Первый столбец - кубы элементов массива
# Второй - квадраты и т.д.
np.vander([1, 2, 3, 4], 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

## NumPy-способы создания многомерных массивов

Для создания массивов произвольной формы (многомерная таблица в математике называется _тензором_) применяются функции [`np.zeros`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros), [`np.ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones), [`np.full`](https://numpy.org/doc/stable/reference/generated/numpy.full.html) и [`random`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random).

```{note}
О генераторах случайных чисел, в т.ч. в NumPy, см. {ref}`random_basics`.
```

Функция `np.zeros` создаёт массив заданной формы (размеров), заполненный нулями.

```{note}
Тип данных по умолчанию - `float`.
```

In [20]:
# Одномерный массив
np.zeros(3)

array([0., 0., 0.])

In [21]:
# Двумерный массив
# (обратите внимание, что форма передаётся как кортеж,
# список или массив, а не просто через запятую)
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# То же, но целочисленный вариант
np.zeros((3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
# Трёхмерный массив
np.zeros((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

Функция `np.ones` устроена тем же образом и делает то же самое, но заполняя массив единицами:

In [24]:
np.ones((2, 3, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

Функция `np.full` возвращает массив заданной формы, заполненный заданным значением.
Тип данных определяется по типу переданного значения либо указывается явно.

In [46]:
# (форма, значение)
np.full((2, 3), 3.5)

array([[3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5]])

In [47]:
np.full(3, -1)

array([-1, -1, -1])

Чтобы сгенерировать массив, заполненный псевдослучайными числами используется генератор таких чисел.
Стандартный NumPy-генератор псевдослучайных чисел создаётся просто:

In [25]:
rg = np.random.default_rng()

С помощью этого генератора возможно создавать различные массивы (подробнее в {ref}`random_basics`):

In [26]:
# Матрица, заполненная случайными числами от 0 до 1
rg.random((5, 3))

array([[0.98462385, 0.68552705, 0.56263481],
       [0.07286761, 0.42083566, 0.20807132],
       [0.24953809, 0.53211833, 0.92611146],
       [0.63338568, 0.3804023 , 0.69302908],
       [0.88190453, 0.17038277, 0.98509834]])

NumPy также имеет функцию создания массива индексов [`np.indices`](https://numpy.org/doc/stable/reference/generated/numpy.indices.html#numpy.indices).
Создаваемый ею массив индексов полезен для операций с массивами на регулярной сетке.

In [27]:
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

## Создание массива по генератору

Создать массив из генератора позволяет функция [`np.fromiter`](https://numpy.org/doc/stable/reference/generated/numpy.fromiter.html#numpy.fromiter):

In [28]:
np.fromiter((x for x in range(1, 10, 2)), int)

array([1, 3, 5, 7, 9])

Обратите внимание, что данной функции необходимо указывать тип данных, т.к. сам генератор эту информацию не предоставляет.
А NumPy способен эффективно обрабатывать классические массивы, т.е. массивы, у которых все элементы имеют одинаковый тип.

In [29]:
np.fromiter((x for x in [1, -1, 0, 3, -4]), float)

array([ 1., -1.,  0.,  3., -4.])

## Создание массива по функции

Создавать массив, используя обычную Python-функцию, позволяет функция [`np.fromfunction`](https://numpy.org/doc/stable/reference/generated/numpy.fromfunction.html#numpy.fromfunction):

In [30]:
# (создающая функция, форма массива)
np.fromfunction(lambda i, j: i, (2, 2))

array([[0., 0.],
       [1., 1.]])

In [31]:
np.fromfunction(lambda i, j: j, (2, 2))

array([[0., 1.],
       [0., 1.]])

In [32]:
np.fromfunction(lambda i, j: i + j, (3, 3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [33]:
def gen_array(i, j):
    return i*j

np.fromfunction(gen_array, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## Создание подобных массивов

Рассмотренные выше функции `np.zeros`, `np.ones` и `np.full` имеют близкие по результату функции [`np.zeros_like`](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html), [`np.ones_like`](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like) и [`np.full_like`](https://numpy.org/doc/stable/reference/generated/numpy.full_like.html#numpy.full_like).
Новые функции на вход принимают не форму нового массива, а другой массив, из которого и берут форму и тип данных.

In [35]:
# Пусть есть массив со случайными целыми числами
a = rg.integers(-10, 11, size=(3, 5))
a

array([[-4, -4, -4,  9, -5],
       [ 8, -1, -4, -8,  0],
       [ 7, -8, -7, -1, -8]])

In [36]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
# Скопируем массив
b = a.copy()
# И у нового изменим тип данных на float
b.dtype = float
# Как следствие, изменится и тип данных подобного массива
np.ones_like(b)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full_like(a, 77)

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [44]:
np.full_like(a, 0.1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Автоматически тип данных подобного массива не изменяется, а назначается таким же, как у исходного массива.
Изменить это можно, явно указав тип данных:

In [45]:
np.full_like(a, 0.1, dtype=float)

array([[0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1]])

## Создание массивов из файлов

NumPy имеет средства для чтения данных из файлов стандартных (для NumPy) и произвольных форматов.

Для чтения данных из текстового файла (текстовым является не только .txt файл) используется функция [`np.loadtxt`](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy.loadtxt).

Пусть есть CSV-файл `simple.csv` со следующим содержимым:

```csv
x,y
0,0
1,1
2,4
3,9
```

Создать NumPy-массив на его основе несложно:

In [34]:
# Прочитать заданный файл,
# разделителем значений считать запятую,
# не читать первую строку файла (заголовок CSV)
np.loadtxt(
    "simple.csv",
    delimiter=",",
    skiprows=1
)

array([[0., 0.],
       [1., 1.],
       [2., 4.],
       [3., 9.]])

## См. также

1. [Более подробная информация на официальном сайте NumPy](https://numpy.org/doc/stable/user/basics.creation.html).
2. [Подробная информация о чтении и записи файлов в NumPy](https://numpy.org/doc/stable/user/how-to-io.html#how-to-io).
3. {ref}`random_basics`.