# Индексация массивов

In [86]:
import numpy as np

## Индексация элементов

Доступ к отдельному элементу массива осуществляется по его индексу:

In [87]:
# Случай одномерного массива
x = np.arange(10)
x[2]

2

In [88]:
# Всё так же, как и со списками и кортежами Python
x[-2]

8

In [89]:
# Преобразуем в двумерный массив
x.shape = 2, 5
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [90]:
# Случай двумерного массива
x[1, 3]

8

In [91]:
x[1, -1]

9

```{important}
Обратите внимание, что для доступа к элементу массива указывается столько индексов, какую размерность `ndim` имеет массив.
В данном случае массив двумерный и его поле `ndim = 2`, поэтому указав два индекса, мы получили элемент.
Если указать, например, три индекса, то получим ошибку.
Если один - вернётся массив, соответствующий строке.
```

In [92]:
try:
    # Третий индекс лишний - нет такой оси
    print(x[1, 3, 2])
except IndexError as ex:
    # Получаем ошибку индексации
    # и соответствующее сообщение
    print(ex)

too many indices for array: array is 2-dimensional, but 3 were indexed


In [93]:
# Указываем меньшее число индексов -
# получаем, например, вторую строку
print(x[1])

[5 6 7 8 9]


Отметим следующее:

In [95]:
# Результат этого
x[0, 2]

2

In [96]:
# тот же, что и результат этого
x[0][2]

2

Однако второй вариант более медленный, поскольку создаётся промежуточный массив `x[0]`, чего не происходит в первом случае.

## Срезы и обходы



In [97]:
a = np.arange(10)
# Срез от 2-го до 8-го элемента с шагом 2
a[1:7:2]

array([1, 3, 5])

In [98]:
# Срез от предпоследнего до 11-го элемента
a[-2:10]

array([8, 9])

In [99]:
# Срез от 3-го с конца до 4-го с начала
# с шагом -1 (в обратном направлении)
a[-3:3:-1]

array([7, 6, 5, 4])

In [100]:
# Срез с 6 элемента до конца
a[5:]

array([5, 6, 7, 8, 9])

In [101]:
# Срез можно получить, передав в качестве индекса
# список индексов
a[[1, 5, -1]]

array([1, 5, 9])

Срезы используются, чтобы, например, изменить несколько значений в массиве:

In [102]:
# Заменим каждый второй элемент -1,
# начиная со второго элемента (индекс 1)
a[1::2] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Если есть матрица `m`, из которой требуется взять заданную строку или столбец, то это можно сделать так:

In [103]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
# Берём вторую строку
m[1]

array([4, 5, 6])

In [105]:
# Берём первый столбец
# (как срез по всем строкам)
m[:, 0]

array([1, 4, 7])

## Способы индексации размерностей

Создадим трёхмерный массив:

In [106]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [107]:
x[..., 0]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
# Это то же самое
x[:, :, 0]

array([[1, 2, 3],
       [4, 5, 6]])

Добавить в существующий массив новую ось единичной длины возможно с помощью [`np.newaxis`](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis):

In [109]:
x.shape

(2, 3, 1)

In [110]:
# Добавили новую ось как второй индекс
x[:, np.newaxis, :, :].shape

(2, 1, 3, 1)

In [111]:
# То же самое
x[:, None, :, :].shape

(2, 1, 3, 1)

## См. также

[Более подробный гайд по индексации NumPy-массивов](https://numpy.org/doc/stable/user/basics.indexing.html).